<?php
include $get_carousel_html;

$artworks = array();
$artworks[0] = array(
	"title_no" => "Motstandskraft",
	"title_it" => "La forza della resistenza",
	"title_en" => "Resistance",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-01.jpg"
);
$artworks[1] = array(
	"title_no" => "Varsel",
	"title_it" => "Avvertimento",
	"title_en" => "Wistle blow",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-02.jpg"
);
$artworks[2] = array(
	"title_no" => "Smerte",
	"title_it" => "Dolore",
	"title_en" => "Agony",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-03.jpg"
);
$artworks[3] = array(
	"title_no" => "Morgensang",
	"title_it" => "Canzone del mattino",
	"title_en" => "Morning Song",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-04.jpg"
);
$artworks[4] = array(
	"title_no" => "Fly lille fugl",
	"title_it" => "Vola uccellino",
	"title_en" => "Little Bird, Fly",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-05.jpg"
);
$artworks[5] = array(
	"title_no" => "Forkledning",
	"title_it" => "Travestimento",
	"title_en" => "Disguise",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => True,
	"path" => "img-natura-a4/A4-1-06.jpg"
);
$artworks[6] = array(
	"title_no" => "Forsvarsposisjon",
	"title_it" => "Posizione di difesa",
	"title_en" => "Defence Stance",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-07.jpg"
);
$artworks[7] = array(
	"title_no" => "Portrett",
	"title_it" => "Ritratto",
	"title_en" => "Portrait",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-08.jpg"
);
$artworks[8] = array(
	"title_no" => "Kjærtegn",
	"title_it" => "Carezza",
	"title_en" => "Caress",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-09.jpg"
);
$artworks[9] = array(
	"title_no" => "Sjelden fugl",
	"title_it" => "Un uccello raro",
	"title_en" => "Rare Bird",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-10.jpg"
);
$artworks[10] = array(
	"title_no" => "Hårsår",
	"title_it" => "Permaloso",
	"title_en" => "Touchy",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-11.jpg"
);
$artworks[11] = array(
	"title_no" => "Studiofugl",
	"title_it" => "Il merlo dello studio",
	"title_en" => "Studio Bird",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-12.jpg"
);
$artworks[12] = array(
	"title_no" => "Litt kjent figur",
	"title_it" => "Figura un po’ conosciuta",
	"title_en" => "Slightly Familiar Bird",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-13.jpg"
);
$artworks[13] = array(
	"title_no" => "Kittelsens katt",
	"title_it" => "Il gatto di Kittelsen",
	"title_en" => "Kittelsen's Cat",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-14.jpg"
);
$artworks[14] = array(
	"title_no" => "Kjernefamilie",
	"title_it" => "La famiglia",
	"title_en" => "Conjugal Family",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-15.jpg"
);
$artworks[15] = array(
	"title_no" => "Hardfør plante",
	"title_it" => "Pianta resistente",
	"title_en" => "Hardy Plant",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-16.jpg"
);
$artworks[16] = array(
	"title_no" => "Vinter",
	"title_it" => "Inverno",
	"title_en" => "Winter",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-17.jpg"
);
$artworks[17] = array(
	"title_no" => "Jakt",
	"title_it" => "Caccia",
	"title_en" => "Hunt",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t3'],
	"size" => $size['NATURA+A4'],
	"year" => "2014",
	"sold" => False,
	"path" => "img-natura-a4/A4-1-18.jpg"
);
?>