<?php
include $get_carousel_html;

$artworks = array();
$artworks[0] = array(
	"title_no" => "Natura +",
	"title_it" => "Natura +",
	"title_en" => "Natura +",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-07.jpg"
);
$artworks[1] = array(
	"title_no" => "Gudinne mot overmakten",	
	"title_it" => "La dea contro la forza superiore",
	"title_en" => "The Goddess Against Preponderance",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 73 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-02.jpg"
);
$artworks[2] = array(
	"title_no" => "Natt-tjern",
	"title_it" => "Lo stagno notturno",
	"title_en" => "Nocturnal Pond",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 73 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-03.jpg"
);
$artworks[3] = array(
	"title_no" => "Sol etter regn",
	"title_it" => "Sole dopo la pioggia",
	"title_en" => "The Sun After the Rain",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-04.jpg"
);
$artworks[4] = array(
	"title_no" => "Stor elv",
	"title_it" => "Il grande fiume",
	"title_en" => "Great River",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-05.jpg"
);
$artworks[5] = array(
	"title_no" => "Fri flyt",
	"title_it" => "Il libero fluire",
	"title_en" => "Free Flow", 
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-06.jpg"
);
/*$artworks[6] = array(
	"title_no" => "Syklus; sakte, sakte",
	"title_it" => "Ciclo; lento, lento",
	"title_en" => "Cycle; slow, slow", 
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t5'],
	"size" => "120 x 90 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-01.jpg"
);*/
$artworks[7] = array(
	"title_no" => "Sirkus Antico",
	"title_it" => "Circo Antico",
	"title_en" => "Circus Antico",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-08.jpg"
);
$artworks[8] = array(
	"title_no" => "Tidlig vår",
	"title_it" => "L’ inizio della primavera",
	"title_en" => "Early Spring",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "60 x 50 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-09.jpg"
);
$artworks[9] = array(
	"title_no" => "Tåken letter",
	"title_it" => "Si alza la nebbia",
	"title_en" => "Fog Clearing",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",
	"technique" => $technique['t5'],
	"size" => "50 x 70 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-10.jpg"
);
$artworks[10] = array(
	"title_no" => "Endelig et øyeblikks fred",
	"title_it" => "Finalmente un momento di pace",
	"title_en" => "Finally a Moment of Peace",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "50 x 70 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-11.jpg"
);
$artworks[11] = array(
	"title_no" => "Ved Tevere",
	"title_it" => "Sul Tevere",
	"title_en" => "By the Tiber",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "50 x 70 cm",
	"year" => "2012",
	"sold" => true,
	"path" => "img-natura-oil/oil-12.jpg"
);
$artworks[12] = array(
	"title_no" => "Tid",
	"title_it" => "Il tempo",
	"title_en" => "Time",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "50 x 40 cm",
	"year" => "2013",
	"sold" => False,
	"path" => "img-natura-oil/oil-13.jpg"
);
$artworks[13] = array(
	"title_no" => "Gul kjærlighet",
	"title_it" => "Amore giallo",
	"title_en" => "Yellow Love",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "35 x 27 cm",
	"year" => "2013",
	"sold" => True,
	"path" => "img-natura-oil/oil-14.jpg"
);
$artworks[14] = array(
	"title_no" => "Lykkerus",
	"title_it" => "Gioiosa ebbrezza",
	"title_en" => "Euphoria",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "30 x 24 cm",
	"year" => "2012",
	"sold" => True,
	"path" => "img-natura-oil/oil-15.jpg"
);
$artworks[15] = array(
	"title_no" => "Figurer i himmelstorm",
	"title_it" => "Figure nel cielo burracoso",
	"title_en" => "Figures in Storm",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "30 x 24 cm",
	"year" => "2012",
	"sold" => False,
	"path" => "img-natura-oil/oil-16.jpg"
);
$artworks[16] = array(
	"title_no" => "Begrenset revir",
	"title_it" => "Territoro limitato",
	"title_en" => "Limited Territory",
	"series_no" => "Natura +",
	"series_it" => "Natura +",
	"series_en" => "Natura +",	
	"technique" => $technique['t5'],
	"size" => "30 x 40 cm",
	"year" => "2012",
	"sold" => True,
	"path" => "img-natura-oil/oil-17.jpg"
);
?>